[package]
name = "fiddle"
version = "0.1.0"
edition = "2021"
authors = ["Tristan Smith <tristan.smith@pm.me>"]
description = "A small programming language written in Rust."
license = "BSD-3-Clause"

[dependencies]
